server:
  port: 8081
spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://121.37.237.168:8761/eureka

#feign ????????????ribbon
ribbon:
  ReadTimeout: 3000 #???????3s ??????
  ConnectTimeout: 3000 #??????
