server:
  port: 8763
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka,http://peer1:8761/eureka
    register-with-eureka: true
    fetch-registry: false
  instance:
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    hostname: peer3 #主机名称 或者服务的ip
    prefer-ip-address: true #以ip的形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 5 #服务实例的续约时间间隔
