server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://XXXX:3306/springtest?characterEncoding=utf-8&serverTimezone=UTC
    username: XXX
    password: XXX
    driver-class-name: com.mysql.cj.jdbc.Driver
