server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://121.37.237.168:3306/springtest?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: lee961120?!
    driver-class-name: com.mysql.cj.jdbc.Driver
