server:
  port: 8081
spring:
  application:
    name: customer-service
eureka:
  client:
    service-url:
      defaultZone: http://121.37.237.168:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
feign:
#  hystrix:
#    enabled: true
  client:
    config:
      default: # 设置的全局超时时间
        connectTimeout: 5000 # 请求连接的超时时间
        readTimeout: 5000 # 请求处理的超时时间
hystrix:
  command:
    default:
