server:
  port: 9092
spring:
  application:
   name: order-service
  cloud:
   nacos:
    discovery:
     group: SEATA_GROUP
     server-addr: localhost:8848
   seata:
     application-id: ${spring.application.name}
     tx-service-group: project # Seata 事务组编号，用于 TC 集群名
     # Seata 服务配置项，对应 ServiceProperties 类
     service:
       # 虚拟组和分组的映射
       vgroup-mapping:
         project: default
     registry:
       type: nacos
       nacos:
         cluster: default # 使用的 Seata 分组
         serverAddr: localhost:8848 # Nacos 服务地址
  datasource:
    url: jdbc:mysql://121.37.237.168:3306/seata_order?useUnicode=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: lee961120?!
mybatis:
  mapper-locations: classpath:mapper/*.xml





