server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      enabled: true #开启网关
      routes:
        - id: login-service-route #唯一标识。默认是一个UUID
          uri: http://localhost:8081
          #uri: lb://login-service  #lb:loadbalance 开启负载均衡
          predicates: #断言 就是配置网关的规则 https://docs.spring.io/spring-cloud-gateway/docs/3.1.5-SNAPSHOT/reference/html/#gateway-request-predicates-factories
            - Path=/doLogin
          filters:
            - name: RequestRateLimiter #过滤器的名称
              args: #过滤器参数
                key-resolver: "#{@apiKeyResolver}" #限流策略，对应策略的Bean
                redis-rate-limiter.replenishRate: 1 #每秒允许处理的请求数量
                redis-rate-limiter.burstCapacity: 2 #每秒最大处理的请求数量
      discovery:
        locator:
          lower-case-service-id: true #服务使用小写
          enabled: true #
eureka:
  client:
    service-url:
      defaultZone: http://121.37.237.168:8761/eureka
    registry-fetch-interval-seconds: 3 #间隔多久去拉取服务注册信息
  instance:
    hostname: localhost
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
